apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: federation-supergraph
spec:
  name: Federated - Social Media APIS
  protocol: "http"
  do_not_track: false
  use_keyless: true
  active: true
  graphql:
    schema: |-
      type Query {
        user(id: ID!): User!
        users: [User!]!
        post(id: ID!): Post!
        posts: [Post!]!
      }

      type User {
        id: ID!
        name: String!
        username: String!
        email: String!
        address: Address!
        phone: String!
        website: String!
        company: Company!
        posts: [Post!]!
      }

      type Address {
        street: String!
        suite: String!
        city: String!
        zipcode: String!
        geo: GeoLocation!
      }

      type GeoLocation {
        lat: String!
        lng: String!
      }

      type Company {
        name: String!
        catchPhrase: String!
        bs: String!
      }

      type Post {
        id: ID!
        userId: ID!
        title: String!
        body: String!
      }
    enabled: true
    execution_mode: supergraph
    supergraph:
      subgraphs_refs:
        - name: federation-users-subgraph
          namespace: default
        - name: federation-posts-subgraph
          namespace: default
    version: "2"
    playground:
      enabled: true
      path: /playground
  proxy:
    target_url: ""
    strip_listen_path: true
    listen_path: /social-media-apis-federated/
