apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin-go-auth
  use_keyless: false
  protocol: http
  active: true
  use_go_plugin_auth: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  custom_middleware:
    driver: goplugin
#    pre:
#      - name: "AddFooBarHeader"
#        path: "/mnt/tyk-gateway/example-go-plugin_4.1.0_linux_amd64.so"
    auth_check:
        name: "MyPluginCustomAuthCheck"
        path: "/mnt/tyk-gateway/example-go-plugin.so"
