changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - format: binary

dockers:
  - image_templates:
    - "tykio/tyk-operator:latest"
    - "tykio/tyk-operator:v{{ .Major }}"
    - "tykio/tyk-operator:v{{ .Major }}.{{ .Minor }}"
    - "tykio/tyk-operator:{{ .Tag }}"
    extra_files:
    - go.mod
    - go.sum
    - main.go
    - api
    - controllers
    - internal
    - vendor
