changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# https://goreleaser.com/customization/checksum/
checksum:
  disable: true

# https://goreleaser.com/customization/archive/
archives:
  - format: binary

# https://goreleaser.com/customization/build/
builds:
  - skip: true

# https://goreleaser.com/customization/docker/
dockers:
  - image_templates:
    - "tykio/tyk-operator:latest"
    - "tykio/tyk-operator:v{{ .Major }}"
    - "tykio/tyk-operator:v{{ .Major }}.{{ .Minor }}"
    - "tykio/tyk-operator:{{ .Tag }}"
    extra_files:
    - go.mod
    - go.sum
    - main.go
    - api
    - controllers
    - internal
    - vendor
