changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/checksum/
checksum:
  disable: false

# https://goreleaser.com/customization/build/
builds:
  - skip: false
# https://goreleaser.com/customization/release/
release:
  disable: true
# https://goreleaser.com/customization/docker/
dockers:
  - image_templates:
      - "tykio/tyk-operator:latest"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - api
      - controllers
      - pkg
      - vendor
