apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
kind: ControllerManagerConfig
health:
  healthProbeBindAddress: :CONTROLLER_MANAGER_HEALTH_PROBE_PORT
metrics:
  bindAddress: 127.0.0.1:CONTROLLER_MANAGER_METRICS_PORT
webhook:
  port: CONTROLLER_MANAGER_WEBHOOK_PORT
leaderElection:
  leaderElect: true
  resourceName: 91ad8c6e.tyk.io
