apiVersion: tyk.tyk.io/v1alpha1
kind: OperatorContext
metadata:
  name: local-pro-test
spec:
  fromSecret:
    namespace: tyk-operator-system
    name: tyk-operator-conf

---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-with-context
spec:
  context:
    name: local-pro-test
    namespace: default
  name: httpbin-with-context
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin-with-context
    strip_listen_path: true
