apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: client-credentials-api
spec:
  name: client-credentials-api
  active: true
  protocol: http
  use_oauth2: true
  oauth_meta:
    allowed_access_types:
      - client_credentials
    allowed_authorize_types:
      - token
    auth_login_redirect: "http://localhost"
  proxy:
    target_url: http://httpbin.default.svc:8000
    strip_listen_path: true
    listen_path: /httpbin

---

apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: client-credentials-policy

spec:
  access_rights_array:
    - name: client-credentials-api
      namespace: default
      versions:
        - Default
  active: true
  name: client_credentials_policy
  state: active

#  curl http://5efbe56e1bd94ac2831f04b80b865322:MTFlNzJkMWMtOWJmYi00MzU3LTg0MWYtNWI3ZjNhYTExZDNh@${INGRESSIP}/httpbin/oauth/token -d grant_type=client_credentials
#  {"access_token":"5fdb14e97984d6000189765648d9d6fc65334e9e83b293f91d312b5c","expires_in":3600,"token_type":"bearer"}
