apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk
  labels:
    app: tyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tyk
  template:
    metadata:
      labels:
        app: tyk
    spec:
      containers:
        - name: tyk
          image: tykio/tyk-gateway:latest
          imagePullPolicy: Always
          env:
            - name: TYK_LOGLEVEL
              value: debug
          command: ["/opt/tyk-gateway/tyk", "--conf=/etc/tyk-gateway/tyk.json"]
          workingDir: /opt/tyk-gateway
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tyk-conf
              mountPath: /etc/tyk-gateway
            - name: tyk-app-dummy
              mountPath: /opt/tyk-gateway/apps
      volumes:
        - name: tyk-conf
          configMap:
            name: tyk-conf
            items:
              - key: tyk.json
                path: tyk.json
        - name: tyk-app-dummy
          emptyDir: {}
