# Prometheus Monitor Service (Metrics)
TYK_OPERATOR_PROMETHEUS_SERVICEMONITOR_IF_STARTS: null # DO NOT CHANGE This will be replaced by `pre_helm.go` script.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: tyk-operator-controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: tyk-operator-controller-manager
status: TYK_OPERATOR_PROMETHEUS_SERVICEMONITOR_IF_ENDS # DO NOT CHANGE This will be replaced by `pre_helm.go` script.
