# permissions for end users to edit apicatalogues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apicatalogue-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - apicatalogues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apicatalogues/status
  verbs:
  - get
