# permissions for end users to view apidescriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apidescription-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/status
  verbs:
  - get
