# permissions for end users to edit apidescriptions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apidescription-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - apidescriptions/status
  verbs:
  - get
