# permissions for end users to view middlewares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: middleware-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - middlewares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - middlewares/status
  verbs:
  - get
