# permissions for end users to view operatorcontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorcontext-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - operatorcontexts/status
  verbs:
  - get
