# permissions for end users to view portalconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portalconfig-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/status
  verbs:
  - get
