# permissions for end users to edit portalconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portalconfig-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalconfigs/status
  verbs:
  - get
