# permissions for end users to edit portalapicatalogues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portalapicatalogue-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - portalapicatalogues/status
  verbs:
  - get
