# permissions for end users to edit subgraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subgraph-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs/status
  verbs:
  - get
