# permissions for end users to view subgraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subgraph-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - subgraphs/status
  verbs:
  - get
