# permissions for end users to view supergraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supergraph-viewer-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - supergraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - supergraphs/status
  verbs:
  - get
