# permissions for end users to edit tykoasapidefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tykoasapidefinition-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tyk-operator
    app.kubernetes.io/part-of: tyk-operator
    app.kubernetes.io/managed-by: kustomize
  name: tykoasapidefinition-editor-role
rules:
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykoasapidefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tyk.tyk.io
  resources:
  - tykoasapidefinitions/status
  verbs:
  - get
