apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: oauth2
spec:
  name: httpbin
  active: true
  protocol: http
  use_oauth2: true
  oauth_meta:
    allowed_access_types:
      - client_credentials
    allowed_authorize_types:
      - code
    auth_login_redirect: http://localhost
  proxy:
    target_url: http://httpbin.default.svc:8000
    strip_listen_path: true
    listen_path: /httpbin