apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      subgraph: posts
  template:
    metadata:
      labels:
        subgraph: posts
    spec:
      containers:
        - image: zalbiraw/go-api-test-service:v1.0.0
          imagePullPolicy: IfNotPresent
          name: posts
          command:
            - ./posts/server
          ports:
            - containerPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: posts
  labels:
    subgraph: posts
    discovery.tyk.io: subgraph
spec:
  ports:
    - name: http
      port: 4001
      targetPort: 4001
  selector:
    subgraph: posts

---

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: posts
spec:
  name: Posts Subgraph
  protocol: "http"
  do_not_track: false
  use_keyless: true
  active: true
  internal: true
  graphql:
    enabled: true
    execution_mode: subgraph
    graph_ref: posts
    version: "2"
    playground:
      enabled: false
      path: ""
  proxy:
    target_url: http://posts.federation.svc:4001/query
    listen_path: /
    disable_strip_slash: true
