# Dynamic Auth

# In this example, we have a bunch of legacy customers who authenticate with our service using Basic Authentication.
# We want to be able to support API Keys also, where both types of clients hit the same ingress.
# As such, Tyk needs to decide whether to perform Basic Authentication or Auth Token auth check.
#
# In order to achieve this, we need to configure 4 API Definitions inside Tyk.
# 1. EntryPoint API
# 2. BasicAuthInternal API
# 3. AuthTokenInternal API
# 4. ProxyInternal API
#
# When the request hits the ingress route, we configure a URL rewrite to pass the request to either the internal
# BasicAuth api or the AuthToken API.
# the internal APIs will then authenticate request, and assuming the happy path, proxy to the ProxyInternal API.
# The ProxyInternal API is responsible for proxying to the underlying service.
#
# It is worth noting that there are no actual http redirect happening here, meaning that there is no performance penalty
# in performing any of these "Internal Redirects".

---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: entrypoint-api
spec:
  name: Entrypoint API
  protocol: http
  active: true
  proxy:
    listen_path: /entrypoint
    strip_listen_path: true
    # TODO: We should be able to create ROUTES without a target URL.
    target_url: http://dummy.com
  use_keyless: true
  # if Authorization: Basic - redirect to tyk://APIID where APIID is the ID associated with namespace/name basic-auth-internal
  # if Authorization: Bearer - redirect to tyk://APIID where APIID is the ID associated with namespace/name auth-token-internal
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: basic-auth-internal
spec:
  name: BasicAuth Internal API
  protocol: http
  active: true
  internal: true
  use_basic_auth: true
  auth_configs:
    basicAuth:
      auth_header_name: Authorization
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        # redirect all traffic to proxy API
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: auth-token-internal
spec:
  name: AuthToken Internal API
  protocol: http
  active: true
  internal: true
  use_basic_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        # redirect all traffic to proxy API
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: proxy-api
spec:
  name: Proxy API
  protocol: http
  active: true
  internal: true
  proxy:
    target_url: http://httpbin.org
  use_keyless: true
---
