apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-validate
spec:
  name: httpbin-validate
  use_keyless: true
  protocol: http
  active: true
  org_id: acme.com
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin-validate
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        use_extended_paths: true
        paths:
          black_list: []
          ignored: []
          white_list: []
        extended_paths:
          validate_json:
            - error_response_code: 422
              method: POST
              path: /post
              schema_b64: ewogICIkaWQiOiAiaHR0cHM6Ly9leGFtcGxlLmNvbS9wZXJzb24uc2NoZW1hLmpzb24iLAogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDQvc2NoZW1hIyIsCiAgInByb3BlcnRpZXMiOiB7CiAgICAiYWdlIjogewogICAgICAiZGVzY3JpcHRpb24iOiAiQWdlIGluIHllYXJzIHdoaWNoIG11c3QgYmUgZXF1YWwgdG8gb3IgZ3JlYXRlciB0aGFuIHplcm8uIiwKICAgICAgIm1pbmltdW0iOiAwLAogICAgICAidHlwZSI6ICJpbnRlZ2VyIgogICAgfSwKICAgICJmaXJzdE5hbWUiOiB7CiAgICAgICJkZXNjcmlwdGlvbiI6ICJUaGUgcGVyc29uJ3MgZmlyc3QgbmFtZS4iLAogICAgICAidHlwZSI6ICJzdHJpbmciCiAgICB9LAogICAgImxhc3ROYW1lIjogewogICAgICAiZGVzY3JpcHRpb24iOiAiVGhlIHBlcnNvbidzIGxhc3QgbmFtZS4iLAogICAgICAidHlwZSI6ICJzdHJpbmciCiAgICB9CiAgfSwKICAidGl0bGUiOiAiUGVyc29uIiwKICAidHlwZSI6ICJvYmplY3QiCn0=

#curl http://localhost:8081/httpbin-transform/anything -X POST -d '{"foo": "bar"}' -H 'Content-Type: application/json'
#  {
#    "args": {},
#    "data": "{\"bar\": \"bar\"}",
#    "files": {},
#    "form": {},
#    "headers": {
#      "Accept": "*/*",
#      "Accept-Encoding": "gzip",
#      "Content-Length": "14",
#      "Content-Type": "application/json",
#      "Host": "httpbin.org",
#      "User-Agent": "curl/7.71.1",
#      "X-Amzn-Trace-Id": "Root=1-5f7b9a0c-38521f504d5e3ff521049ce7"
#    },
#    "json": {
#      "bar": "bar"
#    },
#    "method": "POST",
#    "origin": "::1, 82.47.141.120",
#    "url": "http://httpbin.org/anything"
#  }

