apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: http-client-mtls-again
spec:
  name: Httpbin client mutual TLS Again
  active: true
  protocol: http
  proxy:
    listen_path: /httpbin
    target_url: https://httpbin.org
    strip_listen_path: true
  use_mutual_tls_auth: true
  client_certificate_refs:
  - httpbin-secret