apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-global-headers
spec:
  name: httpbin-global-headers
  use_keyless: true
  protocol: http
  active: true
  org_id: acme.com
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin-global-headers
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        use_extended_paths: true
        paths:
          black_list: []
          ignored: []
          white_list: []
        global_headers:
          foo-req: my-foo
          bar-req: my-bar
        global_headers_remove:
          - hello
        global_response_headers:
          # bug
          Foo-Res: foo-res
          Bar-Res: bar-res
        global_response_headers_remove:
          # bug
          - content-type
          - server

#curl http://localhost:8081/httpbin-global-headers/get -H 'Hello: World' -i
#  HTTP/1.1 200 OK
#Access-Control-Allow-Credentials: true
#Access-Control-Allow-Origin: *
#Content-Length: 345
#Content-Type: application/json
#Date: Wed, 23 Sep 2020 23:10:38 GMT
#Server: gunicorn/19.9.0
#X-Ratelimit-Limit: 0
#X-Ratelimit-Remaining: 0
#X-Ratelimit-Reset: 0
#
#  {
#    "args": {},
#    "headers": {
#      "Accept": "*/*",
#      "Accept-Encoding": "gzip",
#      "Bar-Req": "foo-req",
#      "Foo-Req": "foo-req",
#      "Host": "httpbin.org",
#      "User-Agent": "curl/7.71.1",
#      "X-Amzn-Trace-Id": "Root=1-5f6bd5ee-3ca86240b0df983661a40183"
#    },
#    "origin": "::1, 94.14.220.241",
#    "url": "http://httpbin.org/get"
#  }
