##### How to use upstream certificate refs:

#
# First apply this manifest using the command
# "kubectl apply -f config/samples/httpbin_upstream_certmanager_cert.yaml -n tyk"
#
# The operator will try to create the ApiDefinition and will succeed but will log an error that a certificate is missing
# in the cluster for an upstream

# Apply the cert-manager issued TLS certificate using the following command: (we already have an example one in our repo)
# "kubectl apply -f config/samples/tls/upstream/upstream-tls-cert-manager.yaml -n tyk"

# NOTE: the upstream_certificate_refs can hold references to multiple secrets which are used for the domain
# mentioned in the key (currently "*" is used as a wildcard for all the domains)

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin
  use_keyless: true
  upstream_certificate_refs:
    "*": upstream-tls
  protocol: http
  active: true
  proxy:
    target_url: https://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
