#
# `Track Endpoint` allows you to manually select each endpoint for tracking.
# In this example, /get and /headers endpoints will be tracked. After these endpoints receive requests, you can track
# them through the Dashboard.
# In order to see analytics, you need to have Tyk Pump up and running.
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-endpoint-tracking
spec:
  name: httpbin - Endpoint Track
  use_keyless: true
  protocol: http
  active: true
  do_not_track: false
  proxy:
    target_url: http://httpbin.org/
    listen_path: /httpbin
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        use_extended_paths: true
        paths:
          black_list: []
          ignored: []
          white_list: []
        extended_paths:
          track_endpoints:
            - method: GET
              path: "/get"
            - method: GET
              path: "/headers"
