apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin
  use_keyless: true
  protocol: http
  active: true
  certificate_secret_names:
    - tls-httpbin
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: tyk-gw-ingress
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  ingressClassName: tyk
  tls:
    - secretName: tls-httpbin
      hosts:
        - myhttpbin
  rules:
    - host: myhttpbin
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  number: 8000
            path: /httpbin
            pathType: Prefix
