## Append samples you want in your CSV to this file as resources ##
resources:
- tyk_v1alpha1_portalconfig.yaml
- tyk_v1alpha1_tykoas.yaml
- tyk_v1alpha1_tykoasapidefinition.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
