apiVersion: tyk.tyk.io/v1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  use_keyless: true
  protocol: http
  active: true
  org_id: acme.com
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
