apiVersion: tyk.tyk.io/v1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: my foo api 2
  api_id: foo # this is unique identifier for this API definition
  use_keyless: true
  protocol: http
  active: true
  org_id: acme.com
  proxy:
    target_url: http://httpbin.org
    listen_path: /foo
    strip_listen_path: true
