// +build !ignore_autogenerated

/*


Licensed under the Mozilla Public License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.mozilla.org/en-US/MPL/2.0/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionSpec) DeepCopyInto(out *APIDefinitionSpec) {
	*out = *in
	in.Proxy.DeepCopyInto(&out.Proxy)
	if in.DoNotTrack != nil {
		in, out := &in.DoNotTrack, &out.DoNotTrack
		*out = new(bool)
		**out = **in
	}
	out.Auth = in.Auth
	if in.AuthConfigs != nil {
		in, out := &in.AuthConfigs, &out.AuthConfigs
		*out = make(map[string]AuthConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JWTDefaultPolicies != nil {
		in, out := &in.JWTDefaultPolicies, &out.JWTDefaultPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JWTScopeToPolicyMapping != nil {
		in, out := &in.JWTScopeToPolicyMapping, &out.JWTScopeToPolicyMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.VersionDefinition = in.VersionDefinition
	in.VersionData.DeepCopyInto(&out.VersionData)
	in.CustomMiddleware.DeepCopyInto(&out.CustomMiddleware)
	in.CacheOptions.DeepCopyInto(&out.CacheOptions)
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlacklistedIPs != nil {
		in, out := &in.BlacklistedIPs, &out.BlacklistedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseProcessors != nil {
		in, out := &in.ResponseProcessors, &out.ResponseProcessors
		*out = make([]ResponseProcessor, len(*in))
		copy(*out, *in)
	}
	in.CORS.DeepCopyInto(&out.CORS)
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateSecretNames != nil {
		in, out := &in.CertificateSecretNames, &out.CertificateSecretNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GraphQL != nil {
		in, out := &in.GraphQL, &out.GraphQL
		*out = new(GraphQLConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionSpec.
func (in *APIDefinitionSpec) DeepCopy() *APIDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APILimit) DeepCopyInto(out *APILimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APILimit.
func (in *APILimit) DeepCopy() *APILimit {
	if in == nil {
		return nil
	}
	out := new(APILimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessDefinition) DeepCopyInto(out *AccessDefinition) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedURLs != nil {
		in, out := &in.AllowedURLs, &out.AllowedURLs
		*out = make([]AccessSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessDefinition.
func (in *AccessDefinition) DeepCopy() *AccessDefinition {
	if in == nil {
		return nil
	}
	out := new(AccessDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessSpec) DeepCopyInto(out *AccessSpec) {
	*out = *in
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessSpec.
func (in *AccessSpec) DeepCopy() *AccessSpec {
	if in == nil {
		return nil
	}
	out := new(AccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiDefinition) DeepCopyInto(out *ApiDefinition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiDefinition.
func (in *ApiDefinition) DeepCopy() *ApiDefinition {
	if in == nil {
		return nil
	}
	out := new(ApiDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiDefinition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiDefinitionList) DeepCopyInto(out *ApiDefinitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApiDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiDefinitionList.
func (in *ApiDefinitionList) DeepCopy() *ApiDefinitionList {
	if in == nil {
		return nil
	}
	out := new(ApiDefinitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApiDefinitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiDefinitionStatus) DeepCopyInto(out *ApiDefinitionStatus) {
	*out = *in
	if in.LinkedByPolicies != nil {
		in, out := &in.LinkedByPolicies, &out.LinkedByPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiDefinitionStatus.
func (in *ApiDefinitionStatus) DeepCopy() *ApiDefinitionStatus {
	if in == nil {
		return nil
	}
	out := new(ApiDefinitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	out.Signature = in.Signature
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthProviderMeta) DeepCopyInto(out *AuthProviderMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthProviderMeta.
func (in *AuthProviderMeta) DeepCopy() *AuthProviderMeta {
	if in == nil {
		return nil
	}
	out := new(AuthProviderMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthMeta) DeepCopyInto(out *BasicAuthMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthMeta.
func (in *BasicAuthMeta) DeepCopy() *BasicAuthMeta {
	if in == nil {
		return nil
	}
	out := new(BasicAuthMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleManifest) DeepCopyInto(out *BundleManifest) {
	*out = *in
	if in.FileList != nil {
		in, out := &in.FileList, &out.FileList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CustomMiddleware.DeepCopyInto(&out.CustomMiddleware)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleManifest.
func (in *BundleManifest) DeepCopy() *BundleManifest {
	if in == nil {
		return nil
	}
	out := new(BundleManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORS) DeepCopyInto(out *CORS) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedMethods != nil {
		in, out := &in.AllowedMethods, &out.AllowedMethods
		*out = make([]HttpMethod, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExposedHeaders != nil {
		in, out := &in.ExposedHeaders, &out.ExposedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORS.
func (in *CORS) DeepCopy() *CORS {
	if in == nil {
		return nil
	}
	out := new(CORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheMeta) DeepCopyInto(out *CacheMeta) {
	*out = *in
	if in.CacheOnlyResponseCodes != nil {
		in, out := &in.CacheOnlyResponseCodes, &out.CacheOnlyResponseCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheMeta.
func (in *CacheMeta) DeepCopy() *CacheMeta {
	if in == nil {
		return nil
	}
	out := new(CacheMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheOptions) DeepCopyInto(out *CacheOptions) {
	*out = *in
	if in.CacheOnlyResponseCodes != nil {
		in, out := &in.CacheOnlyResponseCodes, &out.CacheOnlyResponseCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.CacheByHeaders != nil {
		in, out := &in.CacheByHeaders, &out.CacheByHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheOptions.
func (in *CacheOptions) DeepCopy() *CacheOptions {
	if in == nil {
		return nil
	}
	out := new(CacheOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckCommand) DeepCopyInto(out *CheckCommand) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckCommand.
func (in *CheckCommand) DeepCopy() *CheckCommand {
	if in == nil {
		return nil
	}
	out := new(CheckCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerMeta) DeepCopyInto(out *CircuitBreakerMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerMeta.
func (in *CircuitBreakerMeta) DeepCopy() *CircuitBreakerMeta {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceConfig) DeepCopyInto(out *DataSourceConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusCodeTypeNameMappings != nil {
		in, out := &in.StatusCodeTypeNameMappings, &out.StatusCodeTypeNameMappings
		*out = make([]StatusCodeTypeNameMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceConfig.
func (in *DataSourceConfig) DeepCopy() *DataSourceConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndPointMeta) DeepCopyInto(out *EndPointMeta) {
	*out = *in
	if in.MethodActions != nil {
		in, out := &in.MethodActions, &out.MethodActions
		*out = make(map[string]EndpointMethodMeta, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndPointMeta.
func (in *EndPointMeta) DeepCopy() *EndPointMeta {
	if in == nil {
		return nil
	}
	out := new(EndPointMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMethodMeta) DeepCopyInto(out *EndpointMethodMeta) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMethodMeta.
func (in *EndpointMethodMeta) DeepCopy() *EndpointMethodMeta {
	if in == nil {
		return nil
	}
	out := new(EndpointMethodMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventHandlerMetaConfig) DeepCopyInto(out *EventHandlerMetaConfig) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make(map[TykEvent][]EventHandlerTriggerConfig, len(*in))
		for key, val := range *in {
			var outVal []EventHandlerTriggerConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]EventHandlerTriggerConfig, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventHandlerMetaConfig.
func (in *EventHandlerMetaConfig) DeepCopy() *EventHandlerMetaConfig {
	if in == nil {
		return nil
	}
	out := new(EventHandlerMetaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventHandlerTriggerConfig) DeepCopyInto(out *EventHandlerTriggerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventHandlerTriggerConfig.
func (in *EventHandlerTriggerConfig) DeepCopy() *EventHandlerTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(EventHandlerTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedPathsSet) DeepCopyInto(out *ExtendedPathsSet) {
	*out = *in
	if in.Ignored != nil {
		in, out := &in.Ignored, &out.Ignored
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WhiteList != nil {
		in, out := &in.WhiteList, &out.WhiteList
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BlackList != nil {
		in, out := &in.BlackList, &out.BlackList
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cached != nil {
		in, out := &in.Cached, &out.Cached
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = make([]TemplateMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformResponse != nil {
		in, out := &in.TransformResponse, &out.TransformResponse
		*out = make([]TemplateMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformJQ != nil {
		in, out := &in.TransformJQ, &out.TransformJQ
		*out = make([]TransformJQMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformJQResponse != nil {
		in, out := &in.TransformJQResponse, &out.TransformJQResponse
		*out = make([]TransformJQMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformHeader != nil {
		in, out := &in.TransformHeader, &out.TransformHeader
		*out = make([]HeaderInjectionMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransformResponseHeader != nil {
		in, out := &in.TransformResponseHeader, &out.TransformResponseHeader
		*out = make([]HeaderInjectionMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvanceCacheConfig != nil {
		in, out := &in.AdvanceCacheConfig, &out.AdvanceCacheConfig
		*out = make([]CacheMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HardTimeouts != nil {
		in, out := &in.HardTimeouts, &out.HardTimeouts
		*out = make([]HardTimeoutMeta, len(*in))
		copy(*out, *in)
	}
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = make([]CircuitBreakerMeta, len(*in))
		copy(*out, *in)
	}
	if in.URLRewrite != nil {
		in, out := &in.URLRewrite, &out.URLRewrite
		*out = make([]URLRewriteMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Virtual != nil {
		in, out := &in.Virtual, &out.Virtual
		*out = make([]VirtualMeta, len(*in))
		copy(*out, *in)
	}
	if in.SizeLimit != nil {
		in, out := &in.SizeLimit, &out.SizeLimit
		*out = make([]RequestSizeMeta, len(*in))
		copy(*out, *in)
	}
	if in.MethodTransforms != nil {
		in, out := &in.MethodTransforms, &out.MethodTransforms
		*out = make([]MethodTransformMeta, len(*in))
		copy(*out, *in)
	}
	if in.TrackEndpoints != nil {
		in, out := &in.TrackEndpoints, &out.TrackEndpoints
		*out = make([]TrackEndpointMeta, len(*in))
		copy(*out, *in)
	}
	if in.DoNotTrackEndpoints != nil {
		in, out := &in.DoNotTrackEndpoints, &out.DoNotTrackEndpoints
		*out = make([]TrackEndpointMeta, len(*in))
		copy(*out, *in)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = make([]InternalMeta, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedPathsSet.
func (in *ExtendedPathsSet) DeepCopy() *ExtendedPathsSet {
	if in == nil {
		return nil
	}
	out := new(ExtendedPathsSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Gateway) DeepCopyInto(out *Gateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Gateway.
func (in *Gateway) DeepCopy() *Gateway {
	if in == nil {
		return nil
	}
	out := new(Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Gateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayList) DeepCopyInto(out *GatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Gateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayList.
func (in *GatewayList) DeepCopy() *GatewayList {
	if in == nil {
		return nil
	}
	out := new(GatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimit) DeepCopyInto(out *GlobalRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimit.
func (in *GlobalRateLimit) DeepCopy() *GlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLConfig) DeepCopyInto(out *GraphQLConfig) {
	*out = *in
	if in.TypeFieldConfigurations != nil {
		in, out := &in.TypeFieldConfigurations, &out.TypeFieldConfigurations
		*out = make([]TypeFieldConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.GraphQLPlayground = in.GraphQLPlayground
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLConfig.
func (in *GraphQLConfig) DeepCopy() *GraphQLConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLPlayground) DeepCopyInto(out *GraphQLPlayground) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLPlayground.
func (in *GraphQLPlayground) DeepCopy() *GraphQLPlayground {
	if in == nil {
		return nil
	}
	out := new(GraphQLPlayground)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardTimeoutMeta) DeepCopyInto(out *HardTimeoutMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardTimeoutMeta.
func (in *HardTimeoutMeta) DeepCopy() *HardTimeoutMeta {
	if in == nil {
		return nil
	}
	out := new(HardTimeoutMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderInjectionMeta) DeepCopyInto(out *HeaderInjectionMeta) {
	*out = *in
	if in.DeleteHeaders != nil {
		in, out := &in.DeleteHeaders, &out.DeleteHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AddHeaders != nil {
		in, out := &in.AddHeaders, &out.AddHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderInjectionMeta.
func (in *HeaderInjectionMeta) DeepCopy() *HeaderInjectionMeta {
	if in == nil {
		return nil
	}
	out := new(HeaderInjectionMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCheckObject) DeepCopyInto(out *HostCheckObject) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]CheckCommand, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCheckObject.
func (in *HostCheckObject) DeepCopy() *HostCheckObject {
	if in == nil {
		return nil
	}
	out := new(HostCheckObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdExtractorConfig) DeepCopyInto(out *IdExtractorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdExtractorConfig.
func (in *IdExtractorConfig) DeepCopy() *IdExtractorConfig {
	if in == nil {
		return nil
	}
	out := new(IdExtractorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalMeta) DeepCopyInto(out *InternalMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalMeta.
func (in *InternalMeta) DeepCopy() *InternalMeta {
	if in == nil {
		return nil
	}
	out := new(InternalMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingConfiguration) DeepCopyInto(out *MappingConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingConfiguration.
func (in *MappingConfiguration) DeepCopy() *MappingConfiguration {
	if in == nil {
		return nil
	}
	out := new(MappingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodTransformMeta) DeepCopyInto(out *MethodTransformMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodTransformMeta.
func (in *MethodTransformMeta) DeepCopy() *MethodTransformMeta {
	if in == nil {
		return nil
	}
	out := new(MethodTransformMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareDefinition) DeepCopyInto(out *MiddlewareDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareDefinition.
func (in *MiddlewareDefinition) DeepCopy() *MiddlewareDefinition {
	if in == nil {
		return nil
	}
	out := new(MiddlewareDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareIdExtractor) DeepCopyInto(out *MiddlewareIdExtractor) {
	*out = *in
	out.ExtractorConfig = in.ExtractorConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareIdExtractor.
func (in *MiddlewareIdExtractor) DeepCopy() *MiddlewareIdExtractor {
	if in == nil {
		return nil
	}
	out := new(MiddlewareIdExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareSection) DeepCopyInto(out *MiddlewareSection) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	if in.PostKeyAuth != nil {
		in, out := &in.PostKeyAuth, &out.PostKeyAuth
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	out.AuthCheck = in.AuthCheck
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	out.IdExtractor = in.IdExtractor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareSection.
func (in *MiddlewareSection) DeepCopy() *MiddlewareSection {
	if in == nil {
		return nil
	}
	out := new(MiddlewareSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationsManager) DeepCopyInto(out *NotificationsManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationsManager.
func (in *NotificationsManager) DeepCopy() *NotificationsManager {
	if in == nil {
		return nil
	}
	out := new(NotificationsManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Meta) DeepCopyInto(out *OAuth2Meta) {
	*out = *in
	if in.AllowedAccessTypes != nil {
		in, out := &in.AllowedAccessTypes, &out.AllowedAccessTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedAuthorizeTypes != nil {
		in, out := &in.AllowedAuthorizeTypes, &out.AllowedAuthorizeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Meta.
func (in *OAuth2Meta) DeepCopy() *OAuth2Meta {
	if in == nil {
		return nil
	}
	out := new(OAuth2Meta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDProviderConfig) DeepCopyInto(out *OIDProviderConfig) {
	*out = *in
	if in.ClientIDs != nil {
		in, out := &in.ClientIDs, &out.ClientIDs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDProviderConfig.
func (in *OIDProviderConfig) DeepCopy() *OIDProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OIDProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDOptions) DeepCopyInto(out *OpenIDOptions) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]OIDProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDOptions.
func (in *OpenIDOptions) DeepCopy() *OpenIDOptions {
	if in == nil {
		return nil
	}
	out := new(OpenIDOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPartitions) DeepCopyInto(out *PolicyPartitions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPartitions.
func (in *PolicyPartitions) DeepCopy() *PolicyPartitions {
	if in == nil {
		return nil
	}
	out := new(PolicyPartitions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Transport.DeepCopyInto(&out.Transport)
	out.ServiceDiscovery = in.ServiceDiscovery
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTransport) DeepCopyInto(out *ProxyTransport) {
	*out = *in
	if in.SSLCipherSuites != nil {
		in, out := &in.SSLCipherSuites, &out.SSLCipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTransport.
func (in *ProxyTransport) DeepCopy() *ProxyTransport {
	if in == nil {
		return nil
	}
	out := new(ProxyTransport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestSigningMeta) DeepCopyInto(out *RequestSigningMeta) {
	*out = *in
	if in.HeaderList != nil {
		in, out := &in.HeaderList, &out.HeaderList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestSigningMeta.
func (in *RequestSigningMeta) DeepCopy() *RequestSigningMeta {
	if in == nil {
		return nil
	}
	out := new(RequestSigningMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestSizeMeta) DeepCopyInto(out *RequestSizeMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestSizeMeta.
func (in *RequestSizeMeta) DeepCopy() *RequestSizeMeta {
	if in == nil {
		return nil
	}
	out := new(RequestSizeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseProcessor) DeepCopyInto(out *ResponseProcessor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseProcessor.
func (in *ResponseProcessor) DeepCopy() *ResponseProcessor {
	if in == nil {
		return nil
	}
	out := new(ResponseProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTrigger) DeepCopyInto(out *RoutingTrigger) {
	*out = *in
	in.Options.DeepCopyInto(&out.Options)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTrigger.
func (in *RoutingTrigger) DeepCopy() *RoutingTrigger {
	if in == nil {
		return nil
	}
	out := new(RoutingTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTriggerOptions) DeepCopyInto(out *RoutingTriggerOptions) {
	*out = *in
	if in.HeaderMatches != nil {
		in, out := &in.HeaderMatches, &out.HeaderMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.QueryValMatches != nil {
		in, out := &in.QueryValMatches, &out.QueryValMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PathPartMatches != nil {
		in, out := &in.PathPartMatches, &out.PathPartMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SessionMetaMatches != nil {
		in, out := &in.SessionMetaMatches, &out.SessionMetaMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestContextMatches != nil {
		in, out := &in.RequestContextMatches, &out.RequestContextMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.PayloadMatches = in.PayloadMatches
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTriggerOptions.
func (in *RoutingTriggerOptions) DeepCopy() *RoutingTriggerOptions {
	if in == nil {
		return nil
	}
	out := new(RoutingTriggerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicy) DeepCopyInto(out *SecurityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicy.
func (in *SecurityPolicy) DeepCopy() *SecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicyList) DeepCopyInto(out *SecurityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicyList.
func (in *SecurityPolicyList) DeepCopy() *SecurityPolicyList {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicySpec) DeepCopyInto(out *SecurityPolicySpec) {
	*out = *in
	if in.AccessRightsArray != nil {
		in, out := &in.AccessRightsArray, &out.AccessRightsArray
		*out = make([]AccessDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AccessRights != nil {
		in, out := &in.AccessRights, &out.AccessRights
		*out = make(map[string]AccessDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Partitions = in.Partitions
	if in.MetaData != nil {
		in, out := &in.MetaData, &out.MetaData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicySpec.
func (in *SecurityPolicySpec) DeepCopy() *SecurityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicyStatus) DeepCopyInto(out *SecurityPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicyStatus.
func (in *SecurityPolicyStatus) DeepCopy() *SecurityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoveryConfiguration) DeepCopyInto(out *ServiceDiscoveryConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoveryConfiguration.
func (in *ServiceDiscoveryConfiguration) DeepCopy() *ServiceDiscoveryConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionProviderMeta) DeepCopyInto(out *SessionProviderMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionProviderMeta.
func (in *SessionProviderMeta) DeepCopy() *SessionProviderMeta {
	if in == nil {
		return nil
	}
	out := new(SessionProviderMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureConfig) DeepCopyInto(out *SignatureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureConfig.
func (in *SignatureConfig) DeepCopy() *SignatureConfig {
	if in == nil {
		return nil
	}
	out := new(SignatureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfig) DeepCopyInto(out *SourceConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfig.
func (in *SourceConfig) DeepCopy() *SourceConfig {
	if in == nil {
		return nil
	}
	out := new(SourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCodeTypeNameMapping) DeepCopyInto(out *StatusCodeTypeNameMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCodeTypeNameMapping.
func (in *StatusCodeTypeNameMapping) DeepCopy() *StatusCodeTypeNameMapping {
	if in == nil {
		return nil
	}
	out := new(StatusCodeTypeNameMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageOptionsConf) DeepCopyInto(out *StorageOptionsConf) {
	*out = *in
	if in.Addrs != nil {
		in, out := &in.Addrs, &out.Addrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageOptionsConf.
func (in *StorageOptionsConf) DeepCopy() *StorageOptionsConf {
	if in == nil {
		return nil
	}
	out := new(StorageOptionsConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringRegexMap) DeepCopyInto(out *StringRegexMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringRegexMap.
func (in *StringRegexMap) DeepCopy() *StringRegexMap {
	if in == nil {
		return nil
	}
	out := new(StringRegexMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateData) DeepCopyInto(out *TemplateData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateData.
func (in *TemplateData) DeepCopy() *TemplateData {
	if in == nil {
		return nil
	}
	out := new(TemplateData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMeta) DeepCopyInto(out *TemplateMeta) {
	*out = *in
	out.TemplateData = in.TemplateData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMeta.
func (in *TemplateMeta) DeepCopy() *TemplateMeta {
	if in == nil {
		return nil
	}
	out := new(TemplateMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackEndpointMeta) DeepCopyInto(out *TrackEndpointMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackEndpointMeta.
func (in *TrackEndpointMeta) DeepCopy() *TrackEndpointMeta {
	if in == nil {
		return nil
	}
	out := new(TrackEndpointMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformJQMeta) DeepCopyInto(out *TransformJQMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformJQMeta.
func (in *TransformJQMeta) DeepCopy() *TransformJQMeta {
	if in == nil {
		return nil
	}
	out := new(TransformJQMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeFieldConfiguration) DeepCopyInto(out *TypeFieldConfiguration) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = new(MappingConfiguration)
		**out = **in
	}
	in.DataSource.DeepCopyInto(&out.DataSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeFieldConfiguration.
func (in *TypeFieldConfiguration) DeepCopy() *TypeFieldConfiguration {
	if in == nil {
		return nil
	}
	out := new(TypeFieldConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLRewriteMeta) DeepCopyInto(out *URLRewriteMeta) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]RoutingTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLRewriteMeta.
func (in *URLRewriteMeta) DeepCopy() *URLRewriteMeta {
	if in == nil {
		return nil
	}
	out := new(URLRewriteMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeTestConfig) DeepCopyInto(out *UptimeTestConfig) {
	*out = *in
	out.ServiceDiscovery = in.ServiceDiscovery
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeTestConfig.
func (in *UptimeTestConfig) DeepCopy() *UptimeTestConfig {
	if in == nil {
		return nil
	}
	out := new(UptimeTestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeTests) DeepCopyInto(out *UptimeTests) {
	*out = *in
	if in.CheckList != nil {
		in, out := &in.CheckList, &out.CheckList
		*out = make([]HostCheckObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeTests.
func (in *UptimeTests) DeepCopy() *UptimeTests {
	if in == nil {
		return nil
	}
	out := new(UptimeTests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatePathMeta) DeepCopyInto(out *ValidatePathMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatePathMeta.
func (in *ValidatePathMeta) DeepCopy() *ValidatePathMeta {
	if in == nil {
		return nil
	}
	out := new(ValidatePathMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionData) DeepCopyInto(out *VersionData) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make(map[string]VersionInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionData.
func (in *VersionData) DeepCopy() *VersionData {
	if in == nil {
		return nil
	}
	out := new(VersionData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionDefinition) DeepCopyInto(out *VersionDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionDefinition.
func (in *VersionDefinition) DeepCopy() *VersionDefinition {
	if in == nil {
		return nil
	}
	out := new(VersionDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfo) DeepCopyInto(out *VersionInfo) {
	*out = *in
	in.Paths.DeepCopyInto(&out.Paths)
	in.ExtendedPaths.DeepCopyInto(&out.ExtendedPaths)
	if in.GlobalHeaders != nil {
		in, out := &in.GlobalHeaders, &out.GlobalHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GlobalHeadersRemove != nil {
		in, out := &in.GlobalHeadersRemove, &out.GlobalHeadersRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GlobalResponseHeaders != nil {
		in, out := &in.GlobalResponseHeaders, &out.GlobalResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GlobalResponseHeadersRemove != nil {
		in, out := &in.GlobalResponseHeadersRemove, &out.GlobalResponseHeadersRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfo.
func (in *VersionInfo) DeepCopy() *VersionInfo {
	if in == nil {
		return nil
	}
	out := new(VersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfoPaths) DeepCopyInto(out *VersionInfoPaths) {
	*out = *in
	if in.Ignored != nil {
		in, out := &in.Ignored, &out.Ignored
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WhiteList != nil {
		in, out := &in.WhiteList, &out.WhiteList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlackList != nil {
		in, out := &in.BlackList, &out.BlackList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfoPaths.
func (in *VersionInfoPaths) DeepCopy() *VersionInfoPaths {
	if in == nil {
		return nil
	}
	out := new(VersionInfoPaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMeta) DeepCopyInto(out *VirtualMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMeta.
func (in *VirtualMeta) DeepCopy() *VirtualMeta {
	if in == nil {
		return nil
	}
	out := new(VirtualMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webhook) DeepCopyInto(out *Webhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webhook.
func (in *Webhook) DeepCopy() *Webhook {
	if in == nil {
		return nil
	}
	out := new(Webhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Webhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookList) DeepCopyInto(out *WebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Webhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookList.
func (in *WebhookList) DeepCopy() *WebhookList {
	if in == nil {
		return nil
	}
	out := new(WebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSpec) DeepCopyInto(out *WebhookSpec) {
	*out = *in
	if in.HeaderList != nil {
		in, out := &in.HeaderList, &out.HeaderList
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSpec.
func (in *WebhookSpec) DeepCopy() *WebhookSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookStatus) DeepCopyInto(out *WebhookStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookStatus.
func (in *WebhookStatus) DeepCopy() *WebhookStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookStatus)
	in.DeepCopyInto(out)
	return out
}
