//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Mozilla Public License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.mozilla.org/en-US/MPL/2.0/

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package model

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APICatalogue) DeepCopyInto(out *APICatalogue) {
	*out = *in
	if in.APIS != nil {
		in, out := &in.APIS, &out.APIS
		*out = make([]APIDescription, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APICatalogue.
func (in *APICatalogue) DeepCopy() *APICatalogue {
	if in == nil {
		return nil
	}
	out := new(APICatalogue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionSpec) DeepCopyInto(out *APIDefinitionSpec) {
	*out = *in
	in.Proxy.DeepCopyInto(&out.Proxy)
	if in.DoNotTrack != nil {
		in, out := &in.DoNotTrack, &out.DoNotTrack
		*out = new(bool)
		**out = **in
	}
	if in.Oauth2Meta != nil {
		in, out := &in.Oauth2Meta, &out.Oauth2Meta
		*out = new(OAuth2Meta)
		(*in).DeepCopyInto(*out)
	}
	out.Auth = in.Auth
	if in.AuthConfigs != nil {
		in, out := &in.AuthConfigs, &out.AuthConfigs
		*out = make(map[string]AuthConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClientCertificates != nil {
		in, out := &in.ClientCertificates, &out.ClientCertificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientCertificateRefs != nil {
		in, out := &in.ClientCertificateRefs, &out.ClientCertificateRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PinnedPublicKeys != nil {
		in, out := &in.PinnedPublicKeys, &out.PinnedPublicKeys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PinnedPublicKeysRefs != nil {
		in, out := &in.PinnedPublicKeysRefs, &out.PinnedPublicKeysRefs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpstreamCertificates != nil {
		in, out := &in.UpstreamCertificates, &out.UpstreamCertificates
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UpstreamCertificateRefs != nil {
		in, out := &in.UpstreamCertificateRefs, &out.UpstreamCertificateRefs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.JWTDefaultPolicies != nil {
		in, out := &in.JWTDefaultPolicies, &out.JWTDefaultPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JWTScopeToPolicyMapping != nil {
		in, out := &in.JWTScopeToPolicyMapping, &out.JWTScopeToPolicyMapping
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.VersionDefinition = in.VersionDefinition
	in.VersionData.DeepCopyInto(&out.VersionData)
	out.GlobalRateLimit = in.GlobalRateLimit
	in.CustomMiddleware.DeepCopyInto(&out.CustomMiddleware)
	in.CacheOptions.DeepCopyInto(&out.CacheOptions)
	if in.AllowedIPs != nil {
		in, out := &in.AllowedIPs, &out.AllowedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlacklistedIPs != nil {
		in, out := &in.BlacklistedIPs, &out.BlacklistedIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseProcessors != nil {
		in, out := &in.ResponseProcessors, &out.ResponseProcessors
		*out = make([]ResponseProcessor, len(*in))
		copy(*out, *in)
	}
	in.CORS.DeepCopyInto(&out.CORS)
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateSecretNames != nil {
		in, out := &in.CertificateSecretNames, &out.CertificateSecretNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigData != nil {
		in, out := &in.ConfigData, &out.ConfigData
		*out = (*in).DeepCopy()
	}
	if in.TagHeaders != nil {
		in, out := &in.TagHeaders, &out.TagHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GraphQL != nil {
		in, out := &in.GraphQL, &out.GraphQL
		*out = new(GraphQLConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionSpec.
func (in *APIDefinitionSpec) DeepCopy() *APIDefinitionSpec {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDefinitionSpecList) DeepCopyInto(out *APIDefinitionSpecList) {
	*out = *in
	if in.Apis != nil {
		in, out := &in.Apis, &out.Apis
		*out = make([]*APIDefinitionSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(APIDefinitionSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDefinitionSpecList.
func (in *APIDefinitionSpecList) DeepCopy() *APIDefinitionSpecList {
	if in == nil {
		return nil
	}
	out := new(APIDefinitionSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDescription) DeepCopyInto(out *APIDescription) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(PortalModelPortalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDescription.
func (in *APIDescription) DeepCopy() *APIDescription {
	if in == nil {
		return nil
	}
	out := new(APIDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIDocumentation) DeepCopyInto(out *APIDocumentation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIDocumentation.
func (in *APIDocumentation) DeepCopy() *APIDocumentation {
	if in == nil {
		return nil
	}
	out := new(APIDocumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	out.Signature = in.Signature
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthProviderMeta) DeepCopyInto(out *AuthProviderMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthProviderMeta.
func (in *AuthProviderMeta) DeepCopy() *AuthProviderMeta {
	if in == nil {
		return nil
	}
	out := new(AuthProviderMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthMeta) DeepCopyInto(out *BasicAuthMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthMeta.
func (in *BasicAuthMeta) DeepCopy() *BasicAuthMeta {
	if in == nil {
		return nil
	}
	out := new(BasicAuthMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleManifest) DeepCopyInto(out *BundleManifest) {
	*out = *in
	if in.FileList != nil {
		in, out := &in.FileList, &out.FileList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CustomMiddleware.DeepCopyInto(&out.CustomMiddleware)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleManifest.
func (in *BundleManifest) DeepCopy() *BundleManifest {
	if in == nil {
		return nil
	}
	out := new(BundleManifest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORS) DeepCopyInto(out *CORS) {
	*out = *in
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedMethods != nil {
		in, out := &in.AllowedMethods, &out.AllowedMethods
		*out = make([]HttpMethod, len(*in))
		copy(*out, *in)
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExposedHeaders != nil {
		in, out := &in.ExposedHeaders, &out.ExposedHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORS.
func (in *CORS) DeepCopy() *CORS {
	if in == nil {
		return nil
	}
	out := new(CORS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheMeta) DeepCopyInto(out *CacheMeta) {
	*out = *in
	if in.CacheOnlyResponseCodes != nil {
		in, out := &in.CacheOnlyResponseCodes, &out.CacheOnlyResponseCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheMeta.
func (in *CacheMeta) DeepCopy() *CacheMeta {
	if in == nil {
		return nil
	}
	out := new(CacheMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheOptions) DeepCopyInto(out *CacheOptions) {
	*out = *in
	if in.CacheOnlyResponseCodes != nil {
		in, out := &in.CacheOnlyResponseCodes, &out.CacheOnlyResponseCodes
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.CacheByHeaders != nil {
		in, out := &in.CacheByHeaders, &out.CacheByHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheOptions.
func (in *CacheOptions) DeepCopy() *CacheOptions {
	if in == nil {
		return nil
	}
	out := new(CacheOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckCommand) DeepCopyInto(out *CheckCommand) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckCommand.
func (in *CheckCommand) DeepCopy() *CheckCommand {
	if in == nil {
		return nil
	}
	out := new(CheckCommand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerMeta) DeepCopyInto(out *CircuitBreakerMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerMeta.
func (in *CircuitBreakerMeta) DeepCopy() *CircuitBreakerMeta {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DCROptions) DeepCopyInto(out *DCROptions) {
	*out = *in
	if in.GrantTypes != nil {
		in, out := &in.GrantTypes, &out.GrantTypes
		*out = make([]GrantTypeEnum, len(*in))
		copy(*out, *in)
	}
	if in.ResponseTypes != nil {
		in, out := &in.ResponseTypes, &out.ResponseTypes
		*out = make([]ResponseTypeEnum, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DCROptions.
func (in *DCROptions) DeepCopy() *DCROptions {
	if in == nil {
		return nil
	}
	out := new(DCROptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceConfig) DeepCopyInto(out *DataSourceConfig) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusCodeTypeNameMappings != nil {
		in, out := &in.StatusCodeTypeNameMappings, &out.StatusCodeTypeNameMappings
		*out = make([]StatusCodeTypeNameMapping, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceConfig.
func (in *DataSourceConfig) DeepCopy() *DataSourceConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailConfigMeta) DeepCopyInto(out *EmailConfigMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailConfigMeta.
func (in *EmailConfigMeta) DeepCopy() *EmailConfigMeta {
	if in == nil {
		return nil
	}
	out := new(EmailConfigMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailCopyOptions) DeepCopyInto(out *EmailCopyOptions) {
	*out = *in
	out.WelcomeEmail = in.WelcomeEmail
	out.APIKeyEmail = in.APIKeyEmail
	out.ResetPasswordEmail = in.ResetPasswordEmail
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailCopyOptions.
func (in *EmailCopyOptions) DeepCopy() *EmailCopyOptions {
	if in == nil {
		return nil
	}
	out := new(EmailCopyOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndPointMeta) DeepCopyInto(out *EndPointMeta) {
	*out = *in
	if in.MethodActions != nil {
		in, out := &in.MethodActions, &out.MethodActions
		*out = make(map[string]EndpointMethodMeta, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndPointMeta.
func (in *EndPointMeta) DeepCopy() *EndPointMeta {
	if in == nil {
		return nil
	}
	out := new(EndPointMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointMethodMeta) DeepCopyInto(out *EndpointMethodMeta) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointMethodMeta.
func (in *EndpointMethodMeta) DeepCopy() *EndpointMethodMeta {
	if in == nil {
		return nil
	}
	out := new(EndpointMethodMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventHandlerMetaConfig) DeepCopyInto(out *EventHandlerMetaConfig) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make(map[TykEvent][]EventHandlerTriggerConfig, len(*in))
		for key, val := range *in {
			var outVal []EventHandlerTriggerConfig
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]EventHandlerTriggerConfig, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventHandlerMetaConfig.
func (in *EventHandlerMetaConfig) DeepCopy() *EventHandlerMetaConfig {
	if in == nil {
		return nil
	}
	out := new(EventHandlerMetaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventHandlerTriggerConfig) DeepCopyInto(out *EventHandlerTriggerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventHandlerTriggerConfig.
func (in *EventHandlerTriggerConfig) DeepCopy() *EventHandlerTriggerConfig {
	if in == nil {
		return nil
	}
	out := new(EventHandlerTriggerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtendedPathsSet) DeepCopyInto(out *ExtendedPathsSet) {
	*out = *in
	if in.Ignored != nil {
		in, out := &in.Ignored, &out.Ignored
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WhiteList != nil {
		in, out := &in.WhiteList, &out.WhiteList
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BlackList != nil {
		in, out := &in.BlackList, &out.BlackList
		*out = make([]EndPointMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cached != nil {
		in, out := &in.Cached, &out.Cached
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = make([]TemplateMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformResponse != nil {
		in, out := &in.TransformResponse, &out.TransformResponse
		*out = make([]TemplateMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformJQ != nil {
		in, out := &in.TransformJQ, &out.TransformJQ
		*out = make([]TransformJQMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformJQResponse != nil {
		in, out := &in.TransformJQResponse, &out.TransformJQResponse
		*out = make([]TransformJQMeta, len(*in))
		copy(*out, *in)
	}
	if in.TransformHeader != nil {
		in, out := &in.TransformHeader, &out.TransformHeader
		*out = make([]HeaderInjectionMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransformResponseHeader != nil {
		in, out := &in.TransformResponseHeader, &out.TransformResponseHeader
		*out = make([]HeaderInjectionMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvanceCacheConfig != nil {
		in, out := &in.AdvanceCacheConfig, &out.AdvanceCacheConfig
		*out = make([]CacheMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HardTimeouts != nil {
		in, out := &in.HardTimeouts, &out.HardTimeouts
		*out = make([]HardTimeoutMeta, len(*in))
		copy(*out, *in)
	}
	if in.CircuitBreaker != nil {
		in, out := &in.CircuitBreaker, &out.CircuitBreaker
		*out = make([]CircuitBreakerMeta, len(*in))
		copy(*out, *in)
	}
	if in.URLRewrite != nil {
		in, out := &in.URLRewrite, &out.URLRewrite
		*out = make([]URLRewriteMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Virtual != nil {
		in, out := &in.Virtual, &out.Virtual
		*out = make([]VirtualMeta, len(*in))
		copy(*out, *in)
	}
	if in.SizeLimit != nil {
		in, out := &in.SizeLimit, &out.SizeLimit
		*out = make([]RequestSizeMeta, len(*in))
		copy(*out, *in)
	}
	if in.MethodTransforms != nil {
		in, out := &in.MethodTransforms, &out.MethodTransforms
		*out = make([]MethodTransformMeta, len(*in))
		copy(*out, *in)
	}
	if in.TrackEndpoints != nil {
		in, out := &in.TrackEndpoints, &out.TrackEndpoints
		*out = make([]TrackEndpointMeta, len(*in))
		copy(*out, *in)
	}
	if in.DoNotTrackEndpoints != nil {
		in, out := &in.DoNotTrackEndpoints, &out.DoNotTrackEndpoints
		*out = make([]TrackEndpointMeta, len(*in))
		copy(*out, *in)
	}
	if in.ValidateJSON != nil {
		in, out := &in.ValidateJSON, &out.ValidateJSON
		*out = make([]ValidatePathMeta, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = make([]InternalMeta, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtendedPathsSet.
func (in *ExtendedPathsSet) DeepCopy() *ExtendedPathsSet {
	if in == nil {
		return nil
	}
	out := new(ExtendedPathsSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimit) DeepCopyInto(out *GlobalRateLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimit.
func (in *GlobalRateLimit) DeepCopy() *GlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLConfig) DeepCopyInto(out *GraphQLConfig) {
	*out = *in
	if in.TypeFieldConfigurations != nil {
		in, out := &in.TypeFieldConfigurations, &out.TypeFieldConfigurations
		*out = make([]TypeFieldConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.GraphQLPlayground = in.GraphQLPlayground
	in.Proxy.DeepCopyInto(&out.Proxy)
	out.Subgraph = in.Subgraph
	in.Supergraph.DeepCopyInto(&out.Supergraph)
	if in.LastSchemaUpdate != nil {
		in, out := &in.LastSchemaUpdate, &out.LastSchemaUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLConfig.
func (in *GraphQLConfig) DeepCopy() *GraphQLConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLEngineConfig) DeepCopyInto(out *GraphQLEngineConfig) {
	*out = *in
	if in.FieldConfigs != nil {
		in, out := &in.FieldConfigs, &out.FieldConfigs
		*out = make([]GraphQLFieldConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]GraphQLEngineDataSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLEngineConfig.
func (in *GraphQLEngineConfig) DeepCopy() *GraphQLEngineConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLEngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLEngineDataSource) DeepCopyInto(out *GraphQLEngineDataSource) {
	*out = *in
	if in.RootFields != nil {
		in, out := &in.RootFields, &out.RootFields
		*out = make([]GraphQLTypeFields, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLEngineDataSource.
func (in *GraphQLEngineDataSource) DeepCopy() *GraphQLEngineDataSource {
	if in == nil {
		return nil
	}
	out := new(GraphQLEngineDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLFieldConfig) DeepCopyInto(out *GraphQLFieldConfig) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLFieldConfig.
func (in *GraphQLFieldConfig) DeepCopy() *GraphQLFieldConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLFieldConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLPlayground) DeepCopyInto(out *GraphQLPlayground) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLPlayground.
func (in *GraphQLPlayground) DeepCopy() *GraphQLPlayground {
	if in == nil {
		return nil
	}
	out := new(GraphQLPlayground)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLProxyConfig) DeepCopyInto(out *GraphQLProxyConfig) {
	*out = *in
	if in.AuthHeaders != nil {
		in, out := &in.AuthHeaders, &out.AuthHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLProxyConfig.
func (in *GraphQLProxyConfig) DeepCopy() *GraphQLProxyConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSubgraphConfig) DeepCopyInto(out *GraphQLSubgraphConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSubgraphConfig.
func (in *GraphQLSubgraphConfig) DeepCopy() *GraphQLSubgraphConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLSubgraphConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSubgraphEntity) DeepCopyInto(out *GraphQLSubgraphEntity) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSubgraphEntity.
func (in *GraphQLSubgraphEntity) DeepCopy() *GraphQLSubgraphEntity {
	if in == nil {
		return nil
	}
	out := new(GraphQLSubgraphEntity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLSupergraphConfig) DeepCopyInto(out *GraphQLSupergraphConfig) {
	*out = *in
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.Subgraphs != nil {
		in, out := &in.Subgraphs, &out.Subgraphs
		*out = make([]GraphQLSubgraphEntity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GlobalHeaders != nil {
		in, out := &in.GlobalHeaders, &out.GlobalHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLSupergraphConfig.
func (in *GraphQLSupergraphConfig) DeepCopy() *GraphQLSupergraphConfig {
	if in == nil {
		return nil
	}
	out := new(GraphQLSupergraphConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphQLTypeFields) DeepCopyInto(out *GraphQLTypeFields) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphQLTypeFields.
func (in *GraphQLTypeFields) DeepCopy() *GraphQLTypeFields {
	if in == nil {
		return nil
	}
	out := new(GraphQLTypeFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardTimeoutMeta) DeepCopyInto(out *HardTimeoutMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardTimeoutMeta.
func (in *HardTimeoutMeta) DeepCopy() *HardTimeoutMeta {
	if in == nil {
		return nil
	}
	out := new(HardTimeoutMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderInjectionMeta) DeepCopyInto(out *HeaderInjectionMeta) {
	*out = *in
	if in.DeleteHeaders != nil {
		in, out := &in.DeleteHeaders, &out.DeleteHeaders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AddHeaders != nil {
		in, out := &in.AddHeaders, &out.AddHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderInjectionMeta.
func (in *HeaderInjectionMeta) DeepCopy() *HeaderInjectionMeta {
	if in == nil {
		return nil
	}
	out := new(HeaderInjectionMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCheckObject) DeepCopyInto(out *HostCheckObject) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]CheckCommand, len(*in))
		copy(*out, *in)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCheckObject.
func (in *HostCheckObject) DeepCopy() *HostCheckObject {
	if in == nil {
		return nil
	}
	out := new(HostCheckObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdExtractorConfig) DeepCopyInto(out *IdExtractorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdExtractorConfig.
func (in *IdExtractorConfig) DeepCopy() *IdExtractorConfig {
	if in == nil {
		return nil
	}
	out := new(IdExtractorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalMeta) DeepCopyInto(out *InternalMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalMeta.
func (in *InternalMeta) DeepCopy() *InternalMeta {
	if in == nil {
		return nil
	}
	out := new(InternalMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListAPIOptions) DeepCopyInto(out *ListAPIOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListAPIOptions.
func (in *ListAPIOptions) DeepCopy() *ListAPIOptions {
	if in == nil {
		return nil
	}
	out := new(ListAPIOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MailOptions) DeepCopyInto(out *MailOptions) {
	*out = *in
	out.EmailCopy = in.EmailCopy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MailOptions.
func (in *MailOptions) DeepCopy() *MailOptions {
	if in == nil {
		return nil
	}
	out := new(MailOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapStringInterfaceType.
func (in *MapStringInterfaceType) DeepCopy() *MapStringInterfaceType {
	if in == nil {
		return nil
	}
	out := new(MapStringInterfaceType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MappingConfiguration) DeepCopyInto(out *MappingConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MappingConfiguration.
func (in *MappingConfiguration) DeepCopy() *MappingConfiguration {
	if in == nil {
		return nil
	}
	out := new(MappingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MethodTransformMeta) DeepCopyInto(out *MethodTransformMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MethodTransformMeta.
func (in *MethodTransformMeta) DeepCopy() *MethodTransformMeta {
	if in == nil {
		return nil
	}
	out := new(MethodTransformMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareDefinition) DeepCopyInto(out *MiddlewareDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareDefinition.
func (in *MiddlewareDefinition) DeepCopy() *MiddlewareDefinition {
	if in == nil {
		return nil
	}
	out := new(MiddlewareDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareIdExtractor) DeepCopyInto(out *MiddlewareIdExtractor) {
	*out = *in
	out.ExtractorConfig = in.ExtractorConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareIdExtractor.
func (in *MiddlewareIdExtractor) DeepCopy() *MiddlewareIdExtractor {
	if in == nil {
		return nil
	}
	out := new(MiddlewareIdExtractor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiddlewareSection) DeepCopyInto(out *MiddlewareSection) {
	*out = *in
	if in.Pre != nil {
		in, out := &in.Pre, &out.Pre
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	if in.PostKeyAuth != nil {
		in, out := &in.PostKeyAuth, &out.PostKeyAuth
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	out.AuthCheck = in.AuthCheck
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = make([]MiddlewareDefinition, len(*in))
		copy(*out, *in)
	}
	out.IdExtractor = in.IdExtractor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiddlewareSection.
func (in *MiddlewareSection) DeepCopy() *MiddlewareSection {
	if in == nil {
		return nil
	}
	out := new(MiddlewareSection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationsManager) DeepCopyInto(out *NotificationsManager) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationsManager.
func (in *NotificationsManager) DeepCopy() *NotificationsManager {
	if in == nil {
		return nil
	}
	out := new(NotificationsManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuth2Meta) DeepCopyInto(out *OAuth2Meta) {
	*out = *in
	if in.AllowedAccessTypes != nil {
		in, out := &in.AllowedAccessTypes, &out.AllowedAccessTypes
		*out = make([]AccessTypeEnum, len(*in))
		copy(*out, *in)
	}
	if in.AllowedAuthorizeTypes != nil {
		in, out := &in.AllowedAuthorizeTypes, &out.AllowedAuthorizeTypes
		*out = make([]AuthorizeTypeEnum, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuth2Meta.
func (in *OAuth2Meta) DeepCopy() *OAuth2Meta {
	if in == nil {
		return nil
	}
	out := new(OAuth2Meta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDProviderConfig) DeepCopyInto(out *OIDProviderConfig) {
	*out = *in
	if in.ClientIDs != nil {
		in, out := &in.ClientIDs, &out.ClientIDs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDProviderConfig.
func (in *OIDProviderConfig) DeepCopy() *OIDProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OIDProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDOptions) DeepCopyInto(out *OpenIDOptions) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]OIDProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDOptions.
func (in *OpenIDOptions) DeepCopy() *OpenIDOptions {
	if in == nil {
		return nil
	}
	out := new(OpenIDOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortalModelPortalConfig) DeepCopyInto(out *PortalModelPortalConfig) {
	*out = *in
	if in.SignUpFields != nil {
		in, out := &in.SignUpFields, &out.SignUpFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyRequestFields != nil {
		in, out := &in.KeyRequestFields, &out.KeyRequestFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MailOptions != nil {
		in, out := &in.MailOptions, &out.MailOptions
		*out = new(MailOptions)
		**out = **in
	}
	if in.DCROptions != nil {
		in, out := &in.DCROptions, &out.DCROptions
		*out = new(DCROptions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortalModelPortalConfig.
func (in *PortalModelPortalConfig) DeepCopy() *PortalModelPortalConfig {
	if in == nil {
		return nil
	}
	out := new(PortalModelPortalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Proxy) DeepCopyInto(out *Proxy) {
	*out = *in
	if in.TargetInternal != nil {
		in, out := &in.TargetInternal, &out.TargetInternal
		*out = new(TargetInternal)
		**out = **in
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Transport.DeepCopyInto(&out.Transport)
	out.ServiceDiscovery = in.ServiceDiscovery
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Proxy.
func (in *Proxy) DeepCopy() *Proxy {
	if in == nil {
		return nil
	}
	out := new(Proxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTransport) DeepCopyInto(out *ProxyTransport) {
	*out = *in
	if in.SSLCipherSuites != nil {
		in, out := &in.SSLCipherSuites, &out.SSLCipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTransport.
func (in *ProxyTransport) DeepCopy() *ProxyTransport {
	if in == nil {
		return nil
	}
	out := new(ProxyTransport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestSigningMeta) DeepCopyInto(out *RequestSigningMeta) {
	*out = *in
	if in.HeaderList != nil {
		in, out := &in.HeaderList, &out.HeaderList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestSigningMeta.
func (in *RequestSigningMeta) DeepCopy() *RequestSigningMeta {
	if in == nil {
		return nil
	}
	out := new(RequestSigningMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestSizeMeta) DeepCopyInto(out *RequestSizeMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestSizeMeta.
func (in *RequestSizeMeta) DeepCopy() *RequestSizeMeta {
	if in == nil {
		return nil
	}
	out := new(RequestSizeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseProcessor) DeepCopyInto(out *ResponseProcessor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseProcessor.
func (in *ResponseProcessor) DeepCopy() *ResponseProcessor {
	if in == nil {
		return nil
	}
	out := new(ResponseProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Result) DeepCopyInto(out *Result) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Result.
func (in *Result) DeepCopy() *Result {
	if in == nil {
		return nil
	}
	out := new(Result)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteToInternal) DeepCopyInto(out *RewriteToInternal) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteToInternal.
func (in *RewriteToInternal) DeepCopy() *RewriteToInternal {
	if in == nil {
		return nil
	}
	out := new(RewriteToInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTrigger) DeepCopyInto(out *RoutingTrigger) {
	*out = *in
	in.Options.DeepCopyInto(&out.Options)
	if in.RewriteToInternal != nil {
		in, out := &in.RewriteToInternal, &out.RewriteToInternal
		*out = new(RewriteToInternal)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTrigger.
func (in *RoutingTrigger) DeepCopy() *RoutingTrigger {
	if in == nil {
		return nil
	}
	out := new(RoutingTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingTriggerOptions) DeepCopyInto(out *RoutingTriggerOptions) {
	*out = *in
	if in.HeaderMatches != nil {
		in, out := &in.HeaderMatches, &out.HeaderMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.QueryValMatches != nil {
		in, out := &in.QueryValMatches, &out.QueryValMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PathPartMatches != nil {
		in, out := &in.PathPartMatches, &out.PathPartMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SessionMetaMatches != nil {
		in, out := &in.SessionMetaMatches, &out.SessionMetaMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestContextMatches != nil {
		in, out := &in.RequestContextMatches, &out.RequestContextMatches
		*out = make(map[string]StringRegexMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PayloadMatches != nil {
		in, out := &in.PayloadMatches, &out.PayloadMatches
		*out = new(StringRegexMap)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingTriggerOptions.
func (in *RoutingTriggerOptions) DeepCopy() *RoutingTriggerOptions {
	if in == nil {
		return nil
	}
	out := new(RoutingTriggerOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceDiscoveryConfiguration) DeepCopyInto(out *ServiceDiscoveryConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceDiscoveryConfiguration.
func (in *ServiceDiscoveryConfiguration) DeepCopy() *ServiceDiscoveryConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServiceDiscoveryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionProviderMeta) DeepCopyInto(out *SessionProviderMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionProviderMeta.
func (in *SessionProviderMeta) DeepCopy() *SessionProviderMeta {
	if in == nil {
		return nil
	}
	out := new(SessionProviderMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignatureConfig) DeepCopyInto(out *SignatureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignatureConfig.
func (in *SignatureConfig) DeepCopy() *SignatureConfig {
	if in == nil {
		return nil
	}
	out := new(SignatureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfig) DeepCopyInto(out *SourceConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfig.
func (in *SourceConfig) DeepCopy() *SourceConfig {
	if in == nil {
		return nil
	}
	out := new(SourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCodeTypeNameMapping) DeepCopyInto(out *StatusCodeTypeNameMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCodeTypeNameMapping.
func (in *StatusCodeTypeNameMapping) DeepCopy() *StatusCodeTypeNameMapping {
	if in == nil {
		return nil
	}
	out := new(StatusCodeTypeNameMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringRegexMap) DeepCopyInto(out *StringRegexMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringRegexMap.
func (in *StringRegexMap) DeepCopy() *StringRegexMap {
	if in == nil {
		return nil
	}
	out := new(StringRegexMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubGraphSpec) DeepCopyInto(out *SubGraphSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubGraphSpec.
func (in *SubGraphSpec) DeepCopy() *SubGraphSpec {
	if in == nil {
		return nil
	}
	out := new(SubGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubGraphStatus) DeepCopyInto(out *SubGraphStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubGraphStatus.
func (in *SubGraphStatus) DeepCopy() *SubGraphStatus {
	if in == nil {
		return nil
	}
	out := new(SubGraphStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuperGraphSpec) DeepCopyInto(out *SuperGraphSpec) {
	*out = *in
	if in.SubgraphRefs != nil {
		in, out := &in.SubgraphRefs, &out.SubgraphRefs
		*out = make([]Target, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuperGraphSpec.
func (in *SuperGraphSpec) DeepCopy() *SuperGraphSpec {
	if in == nil {
		return nil
	}
	out := new(SuperGraphSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetInternal) DeepCopyInto(out *TargetInternal) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetInternal.
func (in *TargetInternal) DeepCopy() *TargetInternal {
	if in == nil {
		return nil
	}
	out := new(TargetInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateData) DeepCopyInto(out *TemplateData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateData.
func (in *TemplateData) DeepCopy() *TemplateData {
	if in == nil {
		return nil
	}
	out := new(TemplateData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMeta) DeepCopyInto(out *TemplateMeta) {
	*out = *in
	out.TemplateData = in.TemplateData
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMeta.
func (in *TemplateMeta) DeepCopy() *TemplateMeta {
	if in == nil {
		return nil
	}
	out := new(TemplateMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackEndpointMeta) DeepCopyInto(out *TrackEndpointMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackEndpointMeta.
func (in *TrackEndpointMeta) DeepCopy() *TrackEndpointMeta {
	if in == nil {
		return nil
	}
	out := new(TrackEndpointMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformJQMeta) DeepCopyInto(out *TransformJQMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformJQMeta.
func (in *TransformJQMeta) DeepCopy() *TransformJQMeta {
	if in == nil {
		return nil
	}
	out := new(TransformJQMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TypeFieldConfiguration) DeepCopyInto(out *TypeFieldConfiguration) {
	*out = *in
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = new(MappingConfiguration)
		**out = **in
	}
	in.DataSource.DeepCopyInto(&out.DataSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TypeFieldConfiguration.
func (in *TypeFieldConfiguration) DeepCopy() *TypeFieldConfiguration {
	if in == nil {
		return nil
	}
	out := new(TypeFieldConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLRewriteMeta) DeepCopyInto(out *URLRewriteMeta) {
	*out = *in
	if in.RewriteToInternal != nil {
		in, out := &in.RewriteToInternal, &out.RewriteToInternal
		*out = new(RewriteToInternal)
		**out = **in
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]RoutingTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLRewriteMeta.
func (in *URLRewriteMeta) DeepCopy() *URLRewriteMeta {
	if in == nil {
		return nil
	}
	out := new(URLRewriteMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeTestConfig) DeepCopyInto(out *UptimeTestConfig) {
	*out = *in
	out.ServiceDiscovery = in.ServiceDiscovery
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeTestConfig.
func (in *UptimeTestConfig) DeepCopy() *UptimeTestConfig {
	if in == nil {
		return nil
	}
	out := new(UptimeTestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UptimeTests) DeepCopyInto(out *UptimeTests) {
	*out = *in
	if in.CheckList != nil {
		in, out := &in.CheckList, &out.CheckList
		*out = make([]HostCheckObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UptimeTests.
func (in *UptimeTests) DeepCopy() *UptimeTests {
	if in == nil {
		return nil
	}
	out := new(UptimeTests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatePathMeta) DeepCopyInto(out *ValidatePathMeta) {
	*out = *in
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatePathMeta.
func (in *ValidatePathMeta) DeepCopy() *ValidatePathMeta {
	if in == nil {
		return nil
	}
	out := new(ValidatePathMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionData) DeepCopyInto(out *VersionData) {
	*out = *in
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make(map[string]VersionInfo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionData.
func (in *VersionData) DeepCopy() *VersionData {
	if in == nil {
		return nil
	}
	out := new(VersionData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionDefinition) DeepCopyInto(out *VersionDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionDefinition.
func (in *VersionDefinition) DeepCopy() *VersionDefinition {
	if in == nil {
		return nil
	}
	out := new(VersionDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfo) DeepCopyInto(out *VersionInfo) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = new(VersionInfoPaths)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtendedPaths != nil {
		in, out := &in.ExtendedPaths, &out.ExtendedPaths
		*out = new(ExtendedPathsSet)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalHeaders != nil {
		in, out := &in.GlobalHeaders, &out.GlobalHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GlobalHeadersRemove != nil {
		in, out := &in.GlobalHeadersRemove, &out.GlobalHeadersRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GlobalResponseHeaders != nil {
		in, out := &in.GlobalResponseHeaders, &out.GlobalResponseHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GlobalResponseHeadersRemove != nil {
		in, out := &in.GlobalResponseHeadersRemove, &out.GlobalResponseHeadersRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfo.
func (in *VersionInfo) DeepCopy() *VersionInfo {
	if in == nil {
		return nil
	}
	out := new(VersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfoPaths) DeepCopyInto(out *VersionInfoPaths) {
	*out = *in
	if in.Ignored != nil {
		in, out := &in.Ignored, &out.Ignored
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WhiteList != nil {
		in, out := &in.WhiteList, &out.WhiteList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlackList != nil {
		in, out := &in.BlackList, &out.BlackList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfoPaths.
func (in *VersionInfoPaths) DeepCopy() *VersionInfoPaths {
	if in == nil {
		return nil
	}
	out := new(VersionInfoPaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMeta) DeepCopyInto(out *VirtualMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMeta.
func (in *VirtualMeta) DeepCopy() *VirtualMeta {
	if in == nil {
		return nil
	}
	out := new(VirtualMeta)
	in.DeepCopyInto(out)
	return out
}
