apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-cert
spec:
  secretName: httpbin-cert-tls
  dnsNames:
    - httpbin
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: selfsigned-issuer
