apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-delete-test
spec:
  api_id: httpbin-delete-test
  name: httpbin-delete-test
  use_standard_auth: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.default.svc:8000
    listen_path: /httpbin-delete-test
    strip_listen_path: true
