apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: workaround-api
spec:
  name: workaround-api
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.default.svc:8000
    listen_path: /workaround-api
    strip_listen_path: true
