# Here we are creating an API definition with MTLS Auth for httpbin 
#
# We assume that TLS secret `my-test-tls` which stores client certificate already exists in the namespace
# you are creating this API
#
# You can generate self signed key pair using below command
# openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes
#
# Create secret for above certificate
# kubectl create secret tls my-test-tls --cert cert.pem --key key.pem

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-client-mtls
spec:
  name: Httpbin Client MTLS
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
  use_mutual_tls_auth: true
  client_certificate_refs:
    - my-test-tls