# k apply -f https://raw.githubusercontent.com/istio/istio/release-1.8/samples/bookinfo/platform/kube/bookinfo.yaml

apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: myapideftemplate
  labels:
    template: "true"
spec:
  name: foo
  protocol: http
  use_keyless: true
  use_standard_auth: false
  active: true
  proxy:
    target_url: http://example.com
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        paths:
          black_list: []
          ignored: []
          white_list: []

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo
  annotations:
    kubernetes.io/ingress.class: tyk
    tyk.io/template: myapideftemplate
spec:
  rules:
    - host: bookinfo.do.poc.tyk.technology
      http:
        paths:
#          - path: /details
#            pathType: Prefix
#            backend:
#              service:
#                name: details
#                port:
#                  number: 9080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: productpage
                port:
                  number: 9080
#          - path: /ratings
#            pathType: Prefix
#            backend:
#              service:
#                name: ratings
#                port:
#                  number: 9080
#          - path: /reviews
#            pathType: Prefix
#            backend:
#              service:
#                name: reviews
#                port:
#                  number: 9080
