apiVersion: v1
data:
  test_oas.json: |-
    {
      "info": {
        "title": "Petstore",
        "version": "1.0.0"
      },
      "openapi": "3.0.3",
      "components": {},
      "paths": {},
      "x-tyk-api-gateway": {
        "info": {
          "name": "Petstore",
          "state": {
            "active": true
          }
        },
        "upstream": {
          "url": "https://petstore.swagger.io/v2"
        },
        "server": {
          "authentication": {
            "enabled": true,
            "stripAuthorizationData": true,
            "securitySchemes": {
              "basicAuth": {
                "disableCaching": true,
                "header": {
                  "enabled": true,
                  "name": "Authorization"
                },
                "enabled": true
              }
            }
          },
          "listenPath": {
            "value": "/petstore/",
            "strip": true
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: cm
  namespace: default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: TykOasApiDefinition
metadata:
  name: petstore-protected
spec:
  tykOAS:
    configmapRef:
      name: cm
      namespace: default
      keyName: test_oas.json
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin
spec:
  name: OAS-Petstore-Security-Policy
  state: active
  active: true
  access_rights_array:
    - name: petstore-protected  # name of the TykOasApiDefinition CR
      namespace: default        # namespace of the TykOasApiDefinition CR
      kind: TykOasApiDefinition # kind of the TykOasApiDefinition CR
  partitions:
    quota: true
    rate_limit: true
    acl: true

