apiVersion: tyk.tyk.io/v1alpha1
kind: TykOASApiDefinition
metadata:
  name: petstore-oas
spec:
  oas_ref:
    name: petstore-oas-doc
    namespace: default
    key_name: petstore.json

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: petstore-oas-doc
data:
    petstore.json: |+
      {
        "components": {
          "securitySchemes": {
            "jwt_test": {
              "bearerFormat": "JWT",
              "scheme": "bearer",
              "type": "http"
            }
          },
          "schemas": {
            "Error": {
              "properties": {
                "code": {
                  "format": "int32",
                  "type": "integer"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "code",
                "message"
              ],
              "type": "object"
            },
            "Pet": {
              "properties": {
                "id": {
                  "format": "int64",
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                },
                "tag": {
                  "type": "string"
                }
              },
              "required": [
                "id",
                "name"
              ],
              "type": "object"
            },
            "Pets": {
              "items": {
                "$ref": "#/components/schemas/Pet"
              },
              "type": "array"
            }
          }
        },
        "info": {
          "license": {
            "name": "MIT"
          },
          "title": "OAS Petstore",
          "version": "1.0.0"
        },
        "openapi": "3.0.3",
        "security": [
         {
            "jwt_test": []
         }
        ],
        "paths": {
          "/pets": {
            "get": {
              "operationId": "listPets",
              "parameters": [
                {
                  "description": "How many items to return at one time (max 100)",
                  "in": "query",
                  "name": "limit",
                  "schema": {
                    "format": "int32",
                    "type": "integer"
                  }
                }
              ],
              "responses": {
                "200": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Pets"
                      }
                    }
                  },
                  "description": "A paged array of pets",
                  "headers": {
                    "x-next": {
                      "description": "A link to the next page of responses",
                      "schema": {
                        "type": "string"
                      }
                    }
                  }
                },
                "default": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Error"
                      }
                    }
                  },
                  "description": "unexpected error"
                }
              },
              "summary": "List all pets",
              "tags": [
                "pets"
              ]
            },
            "post": {
              "operationId": "createPets",
              "responses": {
                "201": {
                  "description": "Null response"
                },
                "default": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Error"
                      }
                    }
                  },
                  "description": "unexpected error"
                }
              },
              "summary": "Create a pet",
              "tags": [
                "pets"
              ]
            }
          },
          "/pets/{petId}": {
            "get": {
              "operationId": "showPetById",
              "parameters": [
                {
                  "description": "The id of the pet to retrieve",
                  "in": "path",
                  "name": "petId",
                  "required": true,
                  "schema": {
                    "type": "string"
                  }
                }
              ],
              "responses": {
                "200": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Pets"
                      }
                    }
                  },
                  "description": "Expected response to a valid request"
                },
                "default": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "$ref": "#/components/schemas/Error"
                      }
                    }
                  },
                  "description": "unexpected error"
                }
              },
              "summary": "Info for a specific pet",
              "tags": [
                "pets"
              ]
            }
          }
        },
        "servers": [
          {
            "url": "http://localhost:8181/"
          },
          {
            "url": "https://petstore.swagger.io/v2"
          },
          {
            "url": "http://petstore.swagger.io/v2"
          }
        ],
        "x-tyk-api-gateway": {
          "info": {
            "name": "OAS Petstore",
            "orgId": "63ec7b5bd22f660001e37e35",
            "state": {
              "active": true
            }
          },
          "server": {
            "listenPath": {
              "strip": true,
              "value": "/"
            },
            "authentication": {
              "enabled": true,
              "stripAuthorizationData": true,
              "securitySchemes": {
                "jwt_test": {
                  "enabled": true,
                  "header": {
                    "enabled": true,
                    "name": "Authorization"
                  },
                  "source": "TFMwdExTMUNSVWRKVGlCUVZVSk1TVU1nUzBWWkxTMHRMUzBLVFVacmQwVjNXVWhMYjFwSmVtb3dRMEZSV1VsTGIxcEplbW93UkVGUlkwUlJaMEZGUlZaekwyODFLM1ZSWWxScVRETmphSGx1VERSM1dHZFZaekpTT1FweE9WVlZPRWsxYlVWdmRsVm1PRFpSV2pkclQwSkpha3AzY1c1NlJERnZiV0ZuWlVWSVYzZElaRUpQTmtJclpFWmhZbTFrVkRsUVQzaG5QVDBLTFMwdExTMUZUa1FnVUZWQ1RFbERJRXRGV1MwdExTMHQ=",
                  "signingMethod": "ecdsa",
                  "identityBaseField": "sub",
                  "policyFieldName": "pol"
                }
              }
            }
          },
          "upstream": {
            "url": "https://petstore.swagger.io/v2"
          }
        }
      }
      
      
