apiVersion: tyk.tyk.io/v1alpha1
kind: APIDescription
metadata:
  name: sample-portal-api
spec:
  docs:
    documentation: "http://httpbin.org/spec.json"
    doc_type: swagger_custom_url
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalConfig
metadata:
  name: sample-portal-config
spec: {}
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalAPICatalogue
metadata:
  name: sample-portal-api
spec:
  apis:
    - name: sample-portal-api
      namespace: default
