apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin protected
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: protect-api
spec:
  name: Policy for portal catalogue
  state: active
  active: true
  access_rights_array:
    - name: httpbin
      namespace: default
      versions:
        - Default
---
apiVersion: tyk.tyk.io/v1alpha1
kind: APIDescription
metadata:
  name: sample-portal-api
spec:
  name: "sample portal config"
  show: true
  auth_type: authToken
  # is_keyless: true
  policyRef:
    name: protect-api
    namespace: default
  docs:
    documentation: "https://httpbin.org/spec.json"
    doc_type: swagger_custom_url
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalConfig
metadata:
  name: sample-portal-config
spec: {}
---
apiVersion: tyk.tyk.io/v1alpha1
kind: PortalAPICatalogue
metadata:
  name: sample-portal-api
spec:
  apis:
    - name: sample-portal-api
      namespace: default
