name: Upload SBOM
on: 
  pull_request:
  push:

jobs:
  sbom:
     uses: TykTechnologies/github-actions/.github/workflows/sbom.yaml@main
     if: ${{ github.event_name  == 'pull_request' ||  github.event_name == 'push' }}
     secrets:
       TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
       DEPDASH_URL: ${{ secrets.DEPDASH_URL }}
       DEPDASH_KEY: ${{ secrets.DEPDASH_KEY }}
       ORG_GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
       DOCKER_IMAGE: "tykio/tyk-operator:latest"
