name: Tyk Operator

on:
  pull_request

jobs:
#  unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout tyk-operator
#        uses: actions/checkout@v2
#      - name: install kubebuilder
#        uses: RyanSiu1995/kubebuilder-action@v1
#        with:
#          version: 2.3.1
#      - name: run tests
#        run: |
#          make test

  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: create kind cluster
        uses: helm/kind-action@v1.0.0
      - name: deploy tyk
        shell: bash
        run: |
          echo "checking CI license expiry"
          jq -Re 'split(".")[1] | @base64d | fromjson | .exp > now' <<< "${{ secrets.DASH_LICENSE }}"
          sh ./ci/deploy_tyk_pro.sh
          echo "installing custom resources"
          make install
          kubectl get crds
