name: Tyk Tests

on:
  pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: create kind cluster
        uses: helm/kind-action@v1.0.0
      - name: install kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1
        with:
          version: 2.3.1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: deploy tyk
        shell: bash
        run: |
          echo "\n\nchecking CI license expiry"
          jq -Re 'split(".")[1] | @base64d | fromjson | .exp > now' <<< "${{ secrets.DASH_LICENSE }}"
          echo "\n\ninstalling cert-manager"
          kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml
          export TYK_DB_LICENSEKEY=${{ secrets.DASH_LICENSE }}
          sh ./ci/deploy_tyk_pro.sh
          echo "\n\ninstalling custom resources"
          make install
          kubectl get crds
          echo "\n\nbootstrapping tyk dashboard (initial org + user)"
          sh ./ci/bootstrap_org.sh
          cat bootstrapped
          echo "\n\nsetting operator dash secrets"
          sh ./ci/operator_secrets.sh

          echo "\n\nbuilding operator"
          make docker-build IMG=tykio/tyk-operator:test
          kind load-image tykio/tyk-operator:test

          echo "\n\ndeploying operator"
          make deploy IMG=tykio/tyk-operator:latest

          echo "\n\nbdd"
          go get github.com/cucumber/godog/cmd/godog@v0.10.0
          cd bdd && godog
