name: Tyk Tests

on:
  pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: create kind cluster
        uses: helm/kind-action@v1.0.0
      - name: install kubebuilder
        uses: RyanSiu1995/kubebuilder-action@v1
        with:
          version: 2.3.1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: deploy tyk
        shell: bash
        run: |
          echo "checking CI license expiry"
          jq -Re 'split(".")[1] | @base64d | fromjson | .exp > now' <<< "${{ secrets.DASH_LICENSE }}"
          export TYK_DB_LICENSEKEY=${{ secrets.DASH_LICENSE }}
          sh ./ci/deploy_tyk_pro.sh
          echo "installing custom resources"
          make install
          kubectl get crds
          echo "bootstrapping tyk dashboard (initial org + user)"
          sh ./ci/bootstrap_org.sh
          cat bootstrapped
          echo "setting operator dash secrets"
          sh ./ci/deploy_operator.sh
          make test
          go get github.com/cucumber/godog/cmd/godog@v0.10.0
          cd bdd && godog
