name: Tyk Operator

on:
  pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.0.0

      - name: Deploy HttpBin
        run: |
          kubectl apply -f ./playground/httpbin/httpbin.yaml
          while [[ $(kubectl get pods -l app=httpbin -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod..." && sleep 10; done
