name: Release

on:
  push:
    branches:
      - master

jobs:
  build-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tyk-operator
        uses: actions/checkout@v2
      - name: build
        run: |
          echo "DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}"
          echo "DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}"
          echo -n ${{secrets.DOCKER_PASSWORD}} | docker login --username ${{secrets.DOCKER_USERNAME}} --password-stdin
          export USERNAME=tykio
          make docker-build IMG=${USERNAME}/tyk-operator:latest
          make docker-push IMG=${USERNAME}/tyk-operator:latest
