name: Release to official Helm repo

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.3

      - name: Read helm chart version
        id: chart-values
        run: echo "version=$(awk '/version:/ {print $2}' helm/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Package helm chart
        run: helm package helm --version ${{ steps.chart-values.outputs.version }}

      - name: Push helm chart
        uses: cloudsmith-io/action@v0.5.2
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "helm"
          owner: "tyk"
          repo: "helm"
          republish: "true"
          file: "tyk-operator-${{ steps.chart-values.outputs.version }}.tgz"
