name: Setup k8s matrix

on:
  workflow_call:
    outputs:
     k8s-matrix: 
      description: "List of k8s version to test against"
      value: ${{ jobs.setup-k8s-matrix.outputs.k8s-matrix }}

jobs:
   setup-k8s-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup k8s matrix for scheduled run
        id: setup-matrix-schedule
        if: ${{ github.event_name  == 'schedule' }}
        run: |
          MATRIX_PARAMS_COMBINATIONS='["v1.19.16","v1.20.15","v1.21.14","v1.22.15","v1.23.12","v1.24.6"]'
          echo "matrix_params=$MATRIX_PARAMS_COMBINATIONS" >> "$GITHUB_ENV"
      - name: Setup k8s matrix for pull request/push
        id: setup-matrix-pr
        if: ${{ github.event_name  == 'pull_request' ||  github.event_name == 'push' }}
        run: |
          MATRIX_PARAMS_COMBINATIONS='["v1.24.6"]'
          echo "matrix_params=$MATRIX_PARAMS_COMBINATIONS" >> "$GITHUB_ENV"
      - name: Decide which matrix to use
        id: decider
        run: |
          echo "::set-output name=k8s-matrix::$MATRIX_VAR"
        env:
          MATRIX_VAR: ${{env.matrix_params}}
    outputs:
     k8s-matrix: ${{ steps.decider.outputs.k8s-matrix }}
    